### ISSUE TITLE
Hard Deadline to publish

### ISSUE THREAD

**Issue by ChaceHunter** [ethereans/TheEtherian#29]
Discuss this week about whether or not we should implement a hard deadline to publish.

When?
What time?
How big of a window?

Please comment.

**Comment by pablanopete** [comment]
Hard deadlines are a must; quality and consistency. 😶

**Comment by MrNebbiolo** [comment]
8pm on Sunday EST?

**Comment by ChaceHunter** [comment]
Fine with me. I like the Sunday evening publish.
