### ISSUE TITLE
Add more links under DApps

### ISSUE THREAD

**Issue by ChaceHunter** [ethereans/TheEtherian#30]
Propose we add all the social media links for each DApp.

If implemented, what should it look like?
Where should it be placed in each post?

Please vote in comments yes or no.

**Comment by pablanopete** [comment]
yes

**Comment by MrNebbiolo** [comment]
If we can figure out how to get all links on one line I'd like to have "slack, twitter, github, facebook, etc).

**Comment by ChaceHunter** [comment]
I got back a very early framework from WebDev guy from Reddit and he is working on just that. Sharing pics in Gitter.

**Comment by ChaceHunter** [comment]
integrated to etherian.world
