### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by ChaceHunter** [ethereans/TheEtherian#31]
Propose we use MailChimp for newsletter.

Will need an email to send from.
I have registered etherianweekly@gmail.com, but in hindsight I don't feel this is a viable long-term option.

Please comment.

**Comment by MrNebbiolo** [comment]
What's wrong with using that address?

**Comment by ChaceHunter** [comment]
Nothing, I suppose. Just didn't know if we were gonna use something like eth@theetherian.com in the future, and the unsure of the logistics of changing the email used to send out the newsletter to subscribers.

**Comment by silversurfer123** [comment]
I'm against using @gmail it sounds really unprofessional and we can get @whatever for free, can't we?
newsletter@etherian.com or something?
